name : demo virtual machine
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: virtual machine
    runs-on: ubuntu-lates
    
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: print and list out content
      run: echo hello there!
      
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.19.3
    - name: go installed
      run:
        go version
        go test -v
  

