name : demo virtual machine
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: virtual machine
    runs-on: ubuntu-lates
    
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: print and list out content
      run: echo hello there!
